service: sls-certification

disabledDeprecations:
  - "*" # To disable all deprecation messages

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
  bucket: sls-certificates

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

provider:
  name: aws
  region: ${opt:region, 'sa-east-1'}
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  # memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    lambdaHashingVersion: 20201221

# package:
#   individually: true

functions:
  generateCertificate:
    handler: src/functions/generateCertificate.handle
    description: "Generate certificate"
    events:
      - http:
          path: /generateCertificate
          method: POST
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:PutItem
        Resource: "arn:aws:dynamodb:${self.provider.region}:*:table/users_certificates"
  verifyCertificate:
      handler: src/functions/verifyCertificate.handle
      description: "Check the validity of a certificate"
      events:
        - http:
            path: /verifyCertificate/{id}
            method: GET
            cors: true
      iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: "arn:aws:dynamodb:${self.provider.region}:*:table/users_certificates"

resources:
  Resources:
    dbCertificateUser:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users_certificates
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
